version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_PATH=/usr/src/app/data/shadowbrook.db
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data  # Ensure data is persistent
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data